name: Flake check

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17

      - name: Run flake check
        run: nix flake check -L --no-write-lock-file ./tests
